### ISSUE TITLE
401 - Unauthorized: Access is denied due to invalid credentials

### ISSUE THREAD

**Issue by pargit** [Tiberriver256/PoshAltiris#14]
Hi
First thank you for this module. it's a life saver :)
now, i have 2 altiris systems in different environments using different credentials (diff domain/user/etc).
one of them is working perfect but the other not.
i'm sure i'm using the correct user/pass combination because i can rdp the server using the same and they are configed as the altiris service credentials.
the error i'm getting is:
PS M:\> Get-CollectionInclusions -collectionItemGuid $main_filter_guid -type ' ' -Server $altiris_server_mis -Credential $altiris_cred
Invoke-RestMethod : 
401 - Unauthorized: Access is denied due to invalid credentials.
Server Error
 
  401 - Unauthorized: Access is denied due to invalid credentials.
  You do not have permission to view this directory or page using the credentials that you supplied.
 
At C:\Users\xxx\Documents\WindowsPowerShell\Modules\PoshAltiris\0.0.3\Public\CollectionManagement.ps1:398 char:9
         Invoke-RestMethod -Uri "https://$Server/$WebServiceUrl" -Meth ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
     FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

i have port 443 opened between the source and the SMP server. maybe i need another port?

thanks
Mor

**Comment by pargit** [comment]
sorry my mistake... i had a mismatch with the  smp servers variables ;)
we can close this as not relevant anymore.
thanks :)

**Comment by Tiberriver256** [comment]
Glad you figured it out and glad you're finding the module useful!
