### ISSUE TITLE
Change function names to approved PS Verb-Noun syntax

### ISSUE THREAD

**Issue by rsteenwyk** [Tiberriver256/PoshAltiris#4]
Nothing much else to say, going to be a boring job :) But many hands make light work.

**Comment by rsteenwyk** [comment]
This is all set in the Functions folder. The PSM1 file still needs to be updated. I'm looking into a couple different ideas for dot sourcing the function files in the PSM1 file instead of having to explicitly declare them there as it makes the build process a bit silly.

**Comment by Tiberriver256** [comment]
Here is a sample we might be able to use:
https://github.com/RamblingCookieMonster/PSStackExchange/blob/master/PSStackExchange/PSStackExchange.psm1

**Comment by Tiberriver256** [comment]
Finished! Broke our installation script though. Opened Issue #10 for this
